version: '3.8'

services:
  ### Service PHP-FPM ###
  php:
    image: php:8.2-fpm
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_fpm_container
    volumes:
      - ./:/var/www/html:cached
    ports:
      - "9000:9000"
    networks:
      - cloud2642_network

  ### Service Nginx ###
  nginx:
    image: nginx:1.25
    container_name: nginx_container
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html:cached
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - cloud2642_network

  ### Service PostgreSQL ###
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_DB: gestion_utilisateur
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: samsoudine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Table.sql:/docker-entrypoint-initdb.d/Table.sql
    networks:
      - cloud2642_network

networks:
  cloud2642_network:
    external: true

volumes:
  postgres_data:

